version: '3.8'

services:
  # --- BASE DE DATOS (MySQL Oficial) ---
  # Requerimiento IE2: Persistencia con volumen nombrado
  db:
    image: mysql:8.0
    container_name: db-innovatech
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: innovatech_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # --- BACKEND DESPACHOS ---
  # Requerimiento IE1: Contenedorización
  back-despachos:
    image: ${DOCKERHUB_USERNAME}/back-despachos:latest
    container_name: back-despachos
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      - DB_ENDPOINT=db
      - DB_PORT=3306
      - DB_NAME=innovatech_db
      - DB_USERNAME=root
      - DB_PASSWORD=root_password

  # --- BACKEND VENTAS ---
  back-ventas:
    image: ${DOCKERHUB_USERNAME}/back-ventas:latest
    container_name: back-ventas
    restart: always
    depends_on:
      - db
    ports:
      - "8082:8081" # Mapea 8082 externo al 8081 interno de Spring
    environment:
      - DB_ENDPOINT=db
      - DB_PORT=3306
      - DB_NAME=innovatech_db
      - DB_USERNAME=root
      - DB_PASSWORD=root_password

  # --- FRONTEND ---
  # Requerimiento IE4: Acceso vía puerto 80
  frontend:
    image: ${DOCKERHUB_USERNAME}/front-despacho:latest
    container_name: frontend-despacho
    restart: always
    ports:
      - "80:80"

# Definición del volumen para persistencia (IE2)
volumes:
  db_data:
	driver: local